producer: remove dead code
nsqio/go-nsq pull request #310
Opened 2020-11-04 14:09 UTC by martin-sucha

connect returns at the switch in all cases, so any code after the
switch is never executed.

2020-11-04 15:00 UTC, jehiah requested changes
Thank you for your contribution, but as you can see from CI this code is exercised.

2020-11-05 08:54 UTC, martin-sucha commented on producer.go
>  	case StateInit:
Indeed. I was confused by the case being empty. Go doesn't have implicit fallthrough.

I think we could make the code a little bit more readable though - which of the following options do you prefer?

A: Add a comment

```go
	switch state := atomic.LoadInt32(&w.state); state {
	case StateInit:
		// continue executing after the switch
	case StateConnected:
		return nil
	default:
		return ErrNotConnected
	}
```

B: Merge StateInit and default cases:

```go
	state := atomic.LoadInt32(&w.state)
	switch  {
	case state == StateConnected:
		return nil
	case state != StateInit:
		return ErrNotConnected
	}
```

C: move code after the switch to a separate function:

```go
	switch state := atomic.LoadInt32(&w.state); state {
	case StateInit:
		return w.initConnection()
	case StateConnected:
		return nil
	default:
		return ErrNotConnected
	}
```

2020-11-07 22:27 UTC, mreiferson commented on producer.go
>  	case StateInit:
Maybe B is the most readable?

2021-01-15 09:37 UTC, martin-sucha commented on producer.go
>  	case StateInit:
I have opened pull request for this change: https://github.com/nsqio/go-nsq/pull/317

2021-01-15 09:37 UTC, martin-sucha commented
Closing in favor of #317

2021-01-15 09:37 UTC, closed without merging